### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jsgr** [zhedh/cloudtop#1]
启动的时候 es报错，链接不上， 如下图，请问怎么处理
![企业微信20240823-093147](https://github.com/user-attachments/assets/7321e714-50e0-49e6-abb0-0496268a3262)

**Comment by zhedh** [comment]
你用的es是哪个版本？

**Comment by zhedh** [comment]
我看你已经解决了，issue 先关闭了，后续补充 es 相关文档
